
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const ADD_TAGS_REQUEST = 'ADD_TAGS_REQUEST';
export const ADD_TAGS_SUCCESS = 'ADD_TAGS_SUCCESS';
export const ADD_TAGS_FAILURE = 'ADD_TAGS_FAILURE';

export const ADD_ADVERTS_REQUEST = 'ADD_ADVERTS_REQUEST';
export const ADD_ADVERTS_SUCCESS = 'ADD_ADVERTS_SUCCESS';
export const ADD_ADVERTS_FAILURE = 'ADD_ADVERTS_FAILURE';

export const ADD_ONE_ADVERT_REQUEST = 'ADD_ONE_ADVERT_REQUEST';
export const ADD_ONE_ADVERT_SUCCESS = 'ADD_ONE_ADVERT_SUCCESS';
export const ADD_ONE_ADVERT_FAILURE = 'ADD_ONE_ADVERT_FAILURE';

export const USER_INTERFACE_RESET_ERROR = 'USER_INTERFACE_RESET_ERROR';
